import React from "react";
import { useSelector } from "react-redux";
import { Bell, Activity, Sparkles, CheckCircle } from "lucide-react";
import { motion } from "motion/react";

export const NotificationPanel = () => {
  const stocks = useSelector((state) => state.stocks.stocks);
  const manifest = useSelector((state) => state.stocks.manifest);

  const alerts = React.useMemo(() => {
    const list = [
      {
        id: "sys-01",
        type: "success",
        title: "Database Compiled Sync Complete",
        desc: `Ingested ${stocks.length} records successfully. Analytical algorithms calibrated to ${manifest?.timestamp ? manifest.timestamp.replace("_", " ") : "today"}.`,
        time: "Just Now",
        icon: CheckCircle,
        color:
          "text-dash-success bg-dash-success/10 border-dash-success/20 shadow-[0_0_15px_rgba(16,185,129,0.05)]",
      },
    ];

    const rsiBreakouts = stocks.filter((s) => s.day_rsi >= 70).slice(0, 2);
    rsiBreakouts.forEach((stock, idx) => {
      list.push({
        id: `rsi-break-${idx}`,
        type: "warning",
        title: `${stock.nse_code} Overbought Alert`,
        desc: `${stock.stock_name} day RSI surged to ${stock.day_rsi.toFixed(1)}. Short-term momentum breakout detected.`,
        time: `${idx + 1}m ago`,
        icon: Activity,
        color:
          "text-amber-400 bg-amber-400/10 border-amber-500/20 shadow-[0_0_15px_rgba(245,158,11,0.05)]",
      });
    });

    const highVolume = stocks
      .filter((s) => s.day_volume > s.week_volume_avg * 2)
      .slice(0, 2);
    highVolume.forEach((stock, idx) => {
      list.push({
        id: `vol-break-${idx}`,
        type: "info",
        title: `${stock.nse_code} High Volume Spike`,
        desc: `Day volume [${(stock.day_volume / 100000).toFixed(1)}L] is more than double its 7-day average. Institutional interest detected.`,
        time: `${idx + 3}m ago`,
        icon: Sparkles,
        color:
          "text-cyan-400 bg-cyan-400/10 border-cyan-400/20 shadow-[0_0_15px_rgba(6,182,212,0.05)]",
      });
    });

    return list;
  }, [stocks, manifest]);

  const listContainer = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: {
        staggerChildren: 0.08,
        delayChildren: 0.1,
      },
    },
  };

  const listItem = {
    hidden: { opacity: 0, x: -10 },
    show: {
      opacity: 1,
      x: 0,
      transition: { type: "spring", stiffness: 260, damping: 20 },
    },
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 15 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: 0.3 }}
      className="p-5 glass-premium rounded-2xl flex flex-col justify-between h-full"
    >
      <div>
        <div className="flex items-center justify-between border-b border-dash-line pb-3 mb-4">
          <div className="flex items-center gap-2">
            <Bell className="w-4 h-4 text-dash-primary animate-pulse" />
            <h4 className="text-xs font-black tracking-wider uppercase font-display text-white">
              Live System Signals
            </h4>
          </div>
          <span className="text-[9px] font-mono text-dash-muted">
            REAL-TIME
          </span>
        </div>

        <motion.div
          variants={listContainer}
          initial="hidden"
          animate="show"
          className="space-y-3 max-h-56 overflow-y-auto pr-1"
        >
          {alerts.map((alert) => {
            const Icon = alert.icon;
            return (
              <motion.div
                key={alert.id}
                variants={listItem}
                whileHover={{ scale: 1.01, x: 2 }}
                className={`p-3 border rounded-xl flex items-start gap-2.5 transition-all duration-200 cursor-pointer ${alert.color}`}
              >
                <Icon className="w-4 h-4 shrink-0 mt-0.5 animate-pulse" />
                <div className="min-w-0">
                  <div className="flex items-center justify-between gap-2">
                    <span className="text-[10px] font-black uppercase tracking-wide text-white leading-none">
                      {alert.title}
                    </span>
                    <span className="text-[8px] font-mono opacity-60 leading-none shrink-0 font-medium">
                      {alert.time}
                    </span>
                  </div>
                  <p className="text-[9.5px] opacity-80 mt-1 leading-relaxed">
                    {alert.desc}
                  </p>
                </div>
              </motion.div>
            );
          })}
        </motion.div>
      </div>

      <div className="mt-4 pt-3 flex items-center justify-between border-t border-dash-line font-mono text-[9px] text-dash-muted">
        <span>GENERATED BY TREND ENGINEER MACHINE SCORING</span>
        <span className="font-extrabold text-dash-success">
          🟢 ENGINE STATUS: ACTIVE
        </span>
      </div>
    </motion.div>
  );
};

export default NotificationPanel;
